$(document).ready(function() {
	/**
	 * 
	 * @calss:User{int id,String name}
	 * @method:public User getUser(int id)
	 * @explain:get one user by id
	 */
	$("#reportButton").bind("click",function(){
		var params = {
				testType : "JUnit",
			};
		$.ajax({
			   type: "POST",
			   url: "test/junittest",
			   contentType: 'application/json;charset=UTF-8', 
			   data: JSON.stringify(params),
			   dataType: 'json',
			   success: function(data){
			     alert( data.testType + "[ " + data.successCount + " ],[ " + data.failCount + " ]");
			   }
		});
	})
	/**
	 * 
	 * @class:User{int id,String name}
	 * @method:public int addUser(User user)
	 * @explain: add one user with the parmeter of name and the field id is generated by incresing
	 */
	$("#userSave").bind("click",function(){
		var params = {
				name: $("#userName").val()
			};
		$.ajax({
			   type: "POST",
			   url: "user/addUser",
			   contentType:'application/json;charset=UTF-8',
			   data: JSON.stringify(params), 
			   dataType: "json",
			   success: function(id){//返回id
			     alert(id);
			   }
		});
	});
	
});